2024-06-03 18:32:30,869:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-06-03 18:32:30,873:INFO:discord.client: logging in using static token
2024-06-03 18:32:32,125:INFO:discord.gateway: Shard ID None has sent the IDENTIFY payload.
2024-06-03 18:32:32,618:INFO:discord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-09nd",{"micros":108124,"calls":["id_created",{"micros":903,"calls":[]},"session_lookup_time",{"micros":304,"calls":[]},"session_lookup_finished",{"micros":17,"calls":[]},"discord-sessions-prd-1-2",{"micros":104947,"calls":["start_session",{"micros":39803,"calls":["discord-api-rpc-75cf44d995-rlr6f",{"micros":36000,"calls":["get_user",{"micros":7328},"get_guilds",{"micros":2316},"send_scheduled_deletion_message",{"micros":5},"guild_join_requests",{"micros":0},"authorized_ip_coro",{"micros":8}]}]},"starting_guild_connect",{"micros":51,"calls":[]},"presence_started",{"micros":27550,"calls":[]},"guilds_started",{"micros":71,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":37417,"calls":[]},"connect_finished",{"micros":37421,"calls":[]},"build_ready",{"micros":46,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}] (Session ID: bfab7b9e4d3e8d8ea0763911419e6136).
2024-06-03 18:33:23,378:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 423, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 349, in summarize
    response = model.generate_content(full_prompt, )
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 812, in generate_content
    response = rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

2024-06-03 18:33:33,379:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 423, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 352, in summarize
    genai.delete_file(i.name)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/files.py", line 93, in delete_file
    client.delete_file(request=request)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/file_service/client.py", line 1014, in delete_file
    rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

2024-06-03 18:33:42,255:INFO:discord.gateway: Timed out receiving packet. Attempting a reconnect.
2024-06-03 18:33:42,255:INFO:discord.client: Got a request to RESUME the websocket.
2024-06-03 18:33:43,014:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2024-06-03 18:33:43,378:INFO:discord.gateway: Shard ID None has successfully RESUMED session bfab7b9e4d3e8d8ea0763911419e6136 under trace ["gateway-prd-us-east1-c-tmkb",{"micros":963,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":250,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-1-2",{"micros":63}]}].
2024-06-03 18:34:34,264:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 423, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 327, in summarize
    images_file_api = await upload_files_async(paths_attachment)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 277, in upload_files_async
    with ThreadPoolExecutor(max_workers=os.cpu_count()) as executor:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 649, in __exit__
    self.shutdown(wait=True)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 235, in shutdown
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):

2024-06-03 18:34:44,265:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 423, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 327, in summarize
    images_file_api = await upload_files_async(paths_attachment)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 277, in upload_files_async
    with ThreadPoolExecutor(max_workers=os.cpu_count()) as executor:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 649, in __exit__
    self.shutdown(wait=True)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 235, in shutdown
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):

2024-06-03 18:34:54,265:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 423, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 327, in summarize
    images_file_api = await upload_files_async(paths_attachment)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 277, in upload_files_async
    with ThreadPoolExecutor(max_workers=os.cpu_count()) as executor:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 649, in __exit__
    self.shutdown(wait=True)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 235, in shutdown
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):

2024-06-03 18:35:04,266:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 423, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 327, in summarize
    images_file_api = await upload_files_async(paths_attachment)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 277, in upload_files_async
    with ThreadPoolExecutor(max_workers=os.cpu_count()) as executor:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 649, in __exit__
    self.shutdown(wait=True)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 235, in shutdown
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):

2024-06-03 18:35:14,266:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 423, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 327, in summarize
    images_file_api = await upload_files_async(paths_attachment)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 277, in upload_files_async
    with ThreadPoolExecutor(max_workers=os.cpu_count()) as executor:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 649, in __exit__
    self.shutdown(wait=True)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 235, in shutdown
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):

2024-06-03 18:35:24,267:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 423, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 327, in summarize
    images_file_api = await upload_files_async(paths_attachment)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 277, in upload_files_async
    with ThreadPoolExecutor(max_workers=os.cpu_count()) as executor:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 649, in __exit__
    self.shutdown(wait=True)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 235, in shutdown
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):

2024-06-03 18:35:34,267:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 423, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 327, in summarize
    images_file_api = await upload_files_async(paths_attachment)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 277, in upload_files_async
    with ThreadPoolExecutor(max_workers=os.cpu_count()) as executor:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 649, in __exit__
    self.shutdown(wait=True)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 235, in shutdown
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):

2024-06-03 18:35:44,268:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 423, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 327, in summarize
    images_file_api = await upload_files_async(paths_attachment)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 277, in upload_files_async
    with ThreadPoolExecutor(max_workers=os.cpu_count()) as executor:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 649, in __exit__
    self.shutdown(wait=True)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 235, in shutdown
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):

2024-06-03 18:35:54,268:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 90 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 423, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 327, in summarize
    images_file_api = await upload_files_async(paths_attachment)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 277, in upload_files_async
    with ThreadPoolExecutor(max_workers=os.cpu_count()) as executor:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 649, in __exit__
    self.shutdown(wait=True)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 235, in shutdown
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):

