2024-05-28 11:15:24,327:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-05-28 11:15:24,331:INFO:discord.client: logging in using static token
2024-05-28 11:15:25,171:INFO:discord.gateway: Shard ID None has sent the IDENTIFY payload.
2024-05-28 11:15:25,676:INFO:discord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-3h93",{"micros":201640,"calls":["id_created",{"micros":848,"calls":[]},"session_lookup_time",{"micros":241,"calls":[]},"session_lookup_finished",{"micros":12,"calls":[]},"discord-sessions-prd-1-89",{"micros":200285,"calls":["start_session",{"micros":169952,"calls":["discord-api-pyupgrade-8f545c597-zcw58",{"micros":163087,"calls":["get_user",{"micros":7044},"get_guilds",{"micros":51975},"send_scheduled_deletion_message",{"micros":6},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":7}]}]},"starting_guild_connect",{"micros":67,"calls":[]},"presence_started",{"micros":209,"calls":[]},"guilds_started",{"micros":76,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":29928,"calls":[]},"connect_finished",{"micros":29933,"calls":[]},"build_ready",{"micros":43,"calls":[]},"clean_ready",{"micros":0,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}] (Session ID: c2c19c5016b7d97f5df4d7e6901bbcf2).
2024-05-28 11:16:16,422:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 405, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 311, in summarize
    images_file_api.append(genai.upload_file(path))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/files.py", line 69, in upload_file
    response = client.create_file(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/client.py", line 77, in create_file
    result = request.execute()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)

2024-05-28 11:16:26,423:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 405, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 311, in summarize
    images_file_api.append(genai.upload_file(path))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/files.py", line 69, in upload_file
    response = client.create_file(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/client.py", line 77, in create_file
    result = request.execute()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 1007, in next_chunk
    resp, content = _retry_request(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)

2024-05-28 11:16:36,423:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 405, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 311, in summarize
    images_file_api.append(genai.upload_file(path))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/files.py", line 69, in upload_file
    response = client.create_file(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/client.py", line 77, in create_file
    result = request.execute()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)

2024-05-28 11:16:46,424:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 405, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 313, in summarize
    i = genai.get_file(i.name)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/files.py", line 85, in get_file
    return file_types.File(client.get_file(name=name))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/file_service/client.py", line 921, in get_file
    response = rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

2024-05-28 11:16:56,424:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 405, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 335, in summarize
    genai.delete_file(i.name)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/files.py", line 93, in delete_file
    client.delete_file(request=request)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/file_service/client.py", line 1014, in delete_file
    rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

2024-05-28 11:17:06,425:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 405, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 335, in summarize
    genai.delete_file(i.name)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/files.py", line 93, in delete_file
    client.delete_file(request=request)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/file_service/client.py", line 1014, in delete_file
    rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

2024-05-28 11:17:08,852:INFO:discord.gateway: Timed out receiving packet. Attempting a reconnect.
2024-05-28 11:17:08,852:INFO:discord.client: Got a request to RESUME the websocket.
2024-05-28 11:17:09,325:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2024-05-28 11:17:09,640:INFO:discord.gateway: Shard ID None has successfully RESUMED session c2c19c5016b7d97f5df4d7e6901bbcf2 under trace ["gateway-prd-us-east1-b-tgds",{"micros":1269,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":252,"calls":[]},"session_lookup_finished",{"micros":11,"calls":[]},"discord-sessions-prd-1-89",{"micros":80}]}].
2024-05-28 11:18:00,575:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 405, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 316, in summarize
    time.sleep(1)

2024-05-28 11:18:10,576:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 405, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 332, in summarize
    response = model.generate_content(full_prompt, )
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 812, in generate_content
    response = rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

2024-05-28 11:18:20,577:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 405, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 332, in summarize
    response = model.generate_content(full_prompt, )
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 812, in generate_content
    response = rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

2024-05-28 11:18:30,577:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 405, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 335, in summarize
    genai.delete_file(i.name)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/files.py", line 93, in delete_file
    client.delete_file(request=request)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/file_service/client.py", line 1014, in delete_file
    rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

2024-05-28 11:18:32,795:INFO:discord.gateway: Timed out receiving packet. Attempting a reconnect.
2024-05-28 11:18:32,795:INFO:discord.client: Got a request to RESUME the websocket.
2024-05-28 11:18:33,273:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2024-05-28 11:18:33,566:INFO:discord.gateway: Shard ID None has successfully RESUMED session c2c19c5016b7d97f5df4d7e6901bbcf2 under trace ["gateway-prd-us-east1-c-dvrr",{"micros":677,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":189,"calls":[]},"session_lookup_finished",{"micros":11,"calls":[]},"discord-sessions-prd-1-89",{"micros":65}]}].
